---
title: "Stat 337 Project"
author: "Aditi, Ade, Daniela"
date: "4/24/2021"
output: pdf_document
---

```{r}

#load data 
install.packages("jsonlite", repos="https://cran.rstudio.com/")
library("jsonlite")
library(dplyr)

json_file <- 'https://datahub.io/machine-learning/breast-cancer/datapackage.json'
json_data <- fromJSON(paste(readLines(json_file), collapse=""))

#get list of all resources:
print(json_data$resources$name)

#print all tabular data(if exists any)
for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
    data <- read.csv(url(path_to_file))
    print(data)
  }
}

#print head of data 
head(data) 
data

groupeddata4049<-filter(data, age == "40-49")
malignancy4049<-c(groupeddata4049$deg.malig)

P<-prop.table(table(malignancy4049[1:89],malignancy4049[2:90]),1)
P
set.seed(123)
#intial probability vector  
pi<-c(0.6,0.2,0.2)
#define states 
degmalignancy<-c(1,2,3)

#length of chain 
n<-1000

#create the chain object
chain<-rep(NA, n)

#initialize chain
chain[1]<-sample(degmalignancy,1,p=pi)
chain[1]

#draw the second value from the chain
(chain[2]<-sample(degmalignancy,1,p=P[chain[1],]))

#keep drawing
for (i in 2:999){
chain[i+1]<-sample(degmalignancy,1,p=P[chain[i],])
} 

#Look at the first 25 elements of the chain.
chain[1:25]


#simulate the chain 10000 times
nsim<-10000

#blank chain object to store freq of transition rates (1 -> 2) for each simulation
freq1_2<-rep(0,nsim)

for(q in 1:nsim){

#create blank chain object the length of n
chain<-rep(NA,n)
#initialize chain
chain[1]<-sample(degmalignancy,1,p=pi)
#populate chain
for(i in 1:(n-1)){
 chain[i+1]<-sample(degmalignancy,1,p=P[chain[i],])
}
#calculate frequency of nucleotide 'c'
freq1_2[q]<-prop.table(table(chain[1:(n-1)],chain[2:n]))[1,2]
}

#confidence interval for transitioning from state 1 -> 2 
alpha<-0.05
z<-qnorm(1-(alpha/2))
z

samp<-freq1_2[1:1000]
phat<-(table(samp)[1])/length(samp)

n<-length(samp)

lowerbound<-phat-(z*sqrt(phat*(1-phat)/n))
upperbound<-phat+(z*sqrt(phat*(1-phat)/n))
c(lowerbound,upperbound)


#Confidence Intervals 
alpha<-0.05
z<-qnorm(1-(alpha/2))
z



samp<-chain[1:1000]
phat1<-(table(samp)[1])/length(samp)
phat2<-(table(samp)[2])/length(samp)
phat3<-(table(samp)[3])/length(samp)

n<-length(samp)

lowerbound<-phat1-(z*sqrt(phat1*(1-phat1)/n))
upperbound<-phat1+(z*sqrt(phat1*(1-phat1)/n))
c(lowerbound,upperbound)

#We can conclude with 95% confidence that the true proportion of degree of malignancy state '1' in the chain is between 0.1723487 and 0.2216513 
#1->2 

```


```{r cars}
summary(cars)
```


```{r pressure, echo=FALSE}
plot(pressure)
```

